
server:
  port: 8089
#Config datasource Driver
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        #初始化大小
        initialSize: 5
        #最小值
        minIdle: 5
        #最大值
        maxActive: 20
        #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
        maxWait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
        timeBetweenEvictionRunsMillis: 60000
        #配置一个连接在池中最小生存的时间
        minEvictableIdleTimeMillis: 300000




#Config mybatis
mybatis:
# mapper interface xml configuration file位置
  mapper-locations: classpath:/mappers/*.xml
#实体类对应的包位置：扫描依赖注入
  type-aliases-package: com.lan.mybatis.pojo
  configuration:
      map-underscore-to-camel-case: true

auth:
  ignoreUrls:
    - /manager/login



#pagehelper分页插件配置

page helper:
  auto-dialect: true
  reasonable: true




